/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarydatabase;

/**
 *
 * @author rosme
 */
public class LibraryDatabaseInterface extends javax.swing.JFrame {
    
    /**
     * Creates new form LibraryDatabaseInterface
     */
    public LibraryDatabaseInterface() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        DLibraryDbV = new javax.swing.JLabel();
        ShowBooksLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookList = new javax.swing.JList<>();
        mainMenu = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        boocAction = new javax.swing.JMenu();
        addBook = new javax.swing.JMenuItem();
        diplayBook = new javax.swing.JMenuItem();
        checkInBook = new javax.swing.JMenuItem();
        checkOutBook = new javax.swing.JMenuItem();
        deleteBook = new javax.swing.JMenuItem();
        requestPendingBook = new javax.swing.JMenuItem();
        accountInquire = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenu();
        sort = new javax.swing.JMenu();
        sortByAuthor = new javax.swing.JMenuItem();
        sortByTitle = new javax.swing.JMenuItem();
        Quit = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem3.setText("jMenuItem3");

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DLibraryDbV.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        DLibraryDbV.setText("Library Database V.3");

        ShowBooksLabel.setText("Book List");

        bookList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(bookList);

        editMenu.setText("Edit ");

        boocAction.setText("Books");

        addBook.setText("Add");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });
        boocAction.add(addBook);

        diplayBook.setText("Display");
        diplayBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diplayBookActionPerformed(evt);
            }
        });
        boocAction.add(diplayBook);

        checkInBook.setText("CheckIn");
        checkInBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInBookActionPerformed(evt);
            }
        });
        boocAction.add(checkInBook);

        checkOutBook.setText("CheckOut");
        checkOutBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBookActionPerformed(evt);
            }
        });
        boocAction.add(checkOutBook);

        deleteBook.setText("Delete");
        deleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookActionPerformed(evt);
            }
        });
        boocAction.add(deleteBook);

        editMenu.add(boocAction);

        requestPendingBook.setText("Request Pending");
        requestPendingBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestPendingBookActionPerformed(evt);
            }
        });
        editMenu.add(requestPendingBook);

        accountInquire.setText("Account Information");
        editMenu.add(accountInquire);

        mainMenu.add(editMenu);

        reportMenu.setText("Report ");

        sort.setText("Sort");

        sortByAuthor.setText("By Author");
        sortByAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByAuthorActionPerformed(evt);
            }
        });
        sort.add(sortByAuthor);

        sortByTitle.setText("By Title");
        sort.add(sortByTitle);

        reportMenu.add(sort);

        mainMenu.add(reportMenu);

        Quit.setText("Quit");
        mainMenu.add(Quit);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DLibraryDbV)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowBooksLabel))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(DLibraryDbV, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ShowBooksLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkInBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInBookActionPerformed
        // TODO add your handling code here:
        new CheckIn().setVisible(true);
    }//GEN-LAST:event_checkInBookActionPerformed

    private void requestPendingBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestPendingBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestPendingBookActionPerformed

    private void sortByAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortByAuthorActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        // TODO add your handling code here:
        new AddBook().setVisible(true);
    }//GEN-LAST:event_addBookActionPerformed

    private void deleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookActionPerformed
        // TODO add your handling code here:
        new DeleteBook().setVisible(true);
    }//GEN-LAST:event_deleteBookActionPerformed

    private void diplayBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diplayBookActionPerformed
        // TODO add your handling code here:
        new DisplayBook().setVisible(true);
    }//GEN-LAST:event_diplayBookActionPerformed

    private void checkOutBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBookActionPerformed
        // TODO add your handling code here:
        new CheckOut().setVisible(true);
    }//GEN-LAST:event_checkOutBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryDatabaseInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryDatabaseInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryDatabaseInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryDatabaseInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryDatabaseInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DLibraryDbV;
    private javax.swing.JMenu Quit;
    private javax.swing.JLabel ShowBooksLabel;
    private javax.swing.JMenuItem accountInquire;
    private javax.swing.JMenuItem addBook;
    private javax.swing.JMenu boocAction;
    private javax.swing.JList<String> bookList;
    private javax.swing.JMenuItem checkInBook;
    private javax.swing.JMenuItem checkOutBook;
    private javax.swing.JMenuItem deleteBook;
    private javax.swing.JMenuItem diplayBook;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu reportMenu;
    private javax.swing.JMenuItem requestPendingBook;
    private javax.swing.JMenu sort;
    private javax.swing.JMenuItem sortByAuthor;
    private javax.swing.JMenuItem sortByTitle;
    // End of variables declaration//GEN-END:variables
}
